name: 'loc'

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./app
        id: loc
      # Use the output from the `loc` step
      - name: Get the LOC
        run: echo "The project has ${{ steps.loc.outputs.locs }} lines of code"
